### ISSUE TITLE
Fuel imbalance

### ISSUE THREAD

**Issue by njanke96** [headwind-msfs/a339x#45]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-05-22T11:47:48+00:00",
    "ref": "refs/tags/v0.200",
    "sha": "89b88a85942045ce719bdcd7fd24002e2e0b196c",
    "actor": "Revyn112",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.200"
}
```

### Describe the bug

Occasionally when flying longer flights, more fuel seems to be used from the left main tank. This happens even though the fuel used by each engine is roughly the same (in the case of the following screenshot, no.1 engine actually used 1000lbs LESS than no.2). Opening the crossfeed valve and turning off the pumps seems to slow down the fuel usage rate in the left tank, to about the same rate as the right tank. 

Crossfeed not working does seem to be an issue upstream https://github.com/flybywiresim/a32nx/issues/3120

I can't find any mention of fuel being pulled from the tank seemingly to nowhere.

### Expected behavior

The rate the fuel is being pulled from each tank should be roughly equal. When opening crossfeed valve and shutting off the left fuel pumps, no fuel should be used and the balance should restore

### Steps to reproduce

Starting at any airport, with fuel control panel all lights off, at cruise the fuel in the left tank decreases faster than in the right.

### Additional info (optional)

I know this one might be hard to reproduce, it happens to me on longer flights more often than it doesn't and I wish I was more aware of any steps to reproduce. I will update here if I figure anything else out. 

The first screenshot is from 1h30m into a flight, the second is after I finished typing this issue (15 minutes since the first screenshot).

![scn](https://user-images.githubusercontent.com/12754124/183261883-ad01dd4f-168b-4385-b05e-e0e772c5fc1d.png)
![scn2](https://user-images.githubusercontent.com/12754124/183261884-b29ae1d1-a987-421a-a2d9-39ea9e8ebaf3.png)

**Comment by st3ph29** [comment]
there's a fix being tested actually

**Comment by njanke96** [comment]
> there's a fix being tested actually
> 
> #44


Thanks for the reply. I did not search in pull requests, my apologies.

**Comment by Onkelpuh** [comment]
is there a solution how we can fix the problem without waiting for the next update?

**Comment by st3ph29** [comment]
yep install the PR#44

**Comment by Onkelpuh** [comment]
> yep installieren Sie die PR#44

thanks

**Comment by Revyn112** [comment]
fixed with next stable update
